server:
  port: 8001

management:
  endpoints:
    web:
      exposure:
        include: '*'

spring:
  application:
    name: service-goods
  cloud:
    nacos:
      discovery:
        server‐addr: localhost:8848


