server:
  port: 8011

management:
  endpoints:
    web:
      exposure:
        include: '*'

spring:
  application:
    name: sentinel-service-goods-8011
  cloud:
    nacos:
      discovery:
        server‐addr: localhost:8848
    sentinel:
      transport:
        dashboard: localhost:8080